# -*- coding: utf-8 -*-
"""chart_official_media_comments

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Zh8LDAiuw4VDwUUtya1K6rlb_OtGNCxx
"""

from google.colab import files

uploaded = files.upload()

# ==========================================
# Stacked Bar Chart:
# Pilot Comments by Month and Official Media
# with Symlog Y-axis
# ==========================================

import pandas as pd
import matplotlib.pyplot as plt

# ------------------------------------------
# 1. Load the dataset
# ------------------------------------------

df = pd.read_csv("official_media_comments_2025.csv")


# ------------------------------------------
# 2. Fill in parent-post information
# ------------------------------------------
# Some rows only contain comment-level information.
# This step fills the parent-post metadata for all comments
# belonging to the same parent post.

parent_columns = [
    "official_account",
    "post_created_at",
    "post_month",
    "keyword_group",
    "keyword_categories",
    "matched_keywords",
    "parent_post_text"
]

for col in parent_columns:
    df[col] = (
        df.groupby("parent_post_id")[col]
          .transform(lambda x: x.ffill().bfill())
    )


# ------------------------------------------
# 3. Rename official media accounts in English
# ------------------------------------------

media_names = {
    "人民日报": "People's Daily",
    "央视新闻": "CCTV News",
    "中国新闻网": "China News Service",
    "新华社": "Xinhua News"
}

df["media"] = df["official_account"].replace(media_names)


# ------------------------------------------
# 4. Check basic counts
# ------------------------------------------

print("Number of comments by official media:")
print(df["media"].value_counts())

print("\nTotal number of comments:")
print(len(df))


# ------------------------------------------
# 5. Count comments by month and media
# ------------------------------------------

monthly_media = (
    df.groupby(["comment_month", "media"])
      .size()
      .unstack(fill_value=0)
)


# ------------------------------------------
# 6. Make sure all months in 2025 are shown
# ------------------------------------------

all_months = pd.period_range(
    "2025-01",
    "2025-12",
    freq="M"
).astype(str)

monthly_media = monthly_media.reindex(
    all_months,
    fill_value=0
)


# ------------------------------------------
# 7. Set media order
# ------------------------------------------

media_order = [
    "People's Daily",
    "CCTV News",
    "China News Service",
    "Xinhua News"
]

# Make sure all media columns exist
for media in media_order:
    if media not in monthly_media.columns:
        monthly_media[media] = 0

monthly_media = monthly_media[media_order]


# ------------------------------------------
# 8. Create stacked bar chart
# ------------------------------------------

fig, ax = plt.subplots(figsize=(11, 6.5))

bottom = pd.Series(
    0,
    index=monthly_media.index,
    dtype=float
)

for media in media_order:

    ax.bar(
        range(len(monthly_media)),
        monthly_media[media].values,
        bottom=bottom.values,
        label=media,
        width=0.72
    )

    bottom += monthly_media[media]


# ------------------------------------------
# 9. Add total number above each bar
# ------------------------------------------

totals = monthly_media.sum(axis=1)

for i, total in enumerate(totals):

    if total > 0:

        ax.text(
            i,
            total * 1.08 if total > 20 else total + 1,
            str(int(total)),
            ha="center",
            va="bottom",
            fontsize=9
        )


# ------------------------------------------
# 10. Add title and axis labels
# ------------------------------------------

ax.set_title(
    "Distribution of Pilot Comments by Month and Official Media, 2025",
    fontsize=15,
    pad=15
)

ax.set_xlabel(
    "Month",
    fontsize=11
)

ax.set_ylabel(
    "Number of Comments",
    fontsize=11
)


# ------------------------------------------
# 11. Set month labels
# ------------------------------------------

month_labels = [
    "Jan", "Feb", "Mar", "Apr",
    "May", "Jun", "Jul", "Aug",
    "Sep", "Oct", "Nov", "Dec"
]

ax.set_xticks(
    range(12)
)

ax.set_xticklabels(
    month_labels
)


# ------------------------------------------
# 12. Use symlog scale
# ------------------------------------------
# This makes small values easier to see while
# still keeping months with zero comments.

ax.set_yscale(
    "symlog",
    linthresh=20
)

ax.set_yticks(
    [0, 5, 10, 20, 50, 100, 200, 500]
)

ax.set_yticklabels(
    ["0", "5", "10", "20", "50", "100", "200", "500"]
)


# ------------------------------------------
# 13. Improve appearance
# ------------------------------------------

ax.legend(
    title="Official Media",
    frameon=False
)

ax.grid(
    axis="y",
    alpha=0.2
)

ax.spines["top"].set_visible(False)
ax.spines["right"].set_visible(False)

ax.set_ylim(
    0,
    totals.max() * 1.25
)

plt.tight_layout()


# ------------------------------------------
# 14. Save the figure
# ------------------------------------------

plt.savefig(
    "pilot_comments_by_month_media_symlog.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()

# ==========================================
# Pie Chart:
# Topic Distribution of Pilot Comments, 2025
# ==========================================

import pandas as pd
import matplotlib.pyplot as plt

# ------------------------------------------
# 1. Load the dataset
# ------------------------------------------

df = pd.read_csv("official_media_comments_2025.csv")


# ------------------------------------------
# 2. Fill parent-post information
# ------------------------------------------
# Some rows only contain comment-level information.
# This step fills the parent-post metadata for all comments
# belonging to the same parent post.

parent_columns = [
    "official_account",
    "post_created_at",
    "post_month",
    "keyword_group",
    "keyword_categories",
    "matched_keywords",
    "parent_post_text"
]

for col in parent_columns:
    df[col] = (
        df.groupby("parent_post_id")[col]
          .transform(lambda x: x.ffill().bfill())
    )


# ------------------------------------------
# 3. Rename topic groups
# ------------------------------------------

topic_names = {
    "fertility": "Fertility",
    "marriage": "Marriage",
    "both": "Marriage & Fertility"
}

df["topic"] = df["keyword_group"].replace(topic_names)


# ------------------------------------------
# 4. Set topic order
# ------------------------------------------

topic_order = [
    "Fertility",
    "Marriage & Fertility",
    "Marriage"
]


# ------------------------------------------
# 5. Count comments by topic
# ------------------------------------------

topic_counts = (
    df["topic"]
    .value_counts()
    .reindex(topic_order)
    .fillna(0)
    .astype(int)
)

print("Number of comments by topic:")
print(topic_counts)

print("\nTotal number of comments:")
print(topic_counts.sum())


# ------------------------------------------
# 6. Function to show percentage + count
# ------------------------------------------

def autopct_with_count(values):
    total = values.sum()

    def format_pct(pct):
        count = int(round(pct * total / 100.0))
        if count == 0:
            return ""
        return f"{pct:.1f}%\n(n={count})"

    return format_pct


# ------------------------------------------
# 7. Choose nicer colors
# ------------------------------------------
# Soft, report-friendly colors

colors = [
    "#7FB3D5",  # soft blue
    "#F5B7B1",  # soft pink
    "#A9DFBF"   # soft green
]


# ------------------------------------------
# 8. Optional: slightly separate slices
# ------------------------------------------

explode = [0.03, 0.03, 0.06]


# ------------------------------------------
# 9. Create pie chart
# ------------------------------------------

fig, ax = plt.subplots(figsize=(8, 6.5))

wedges, texts, autotexts = ax.pie(
    topic_counts.values,
    labels=topic_counts.index,
    colors=colors,
    explode=explode,
    autopct=autopct_with_count(topic_counts.values),
    startangle=90,
    counterclock=False,
    wedgeprops={
        "edgecolor": "white",
        "linewidth": 2
    },
    textprops={
        "fontsize": 10
    }
)


# ------------------------------------------
# 10. Improve text appearance
# ------------------------------------------

for text in texts:
    text.set_fontsize(11)

for autotext in autotexts:
    autotext.set_fontsize(10)
    autotext.set_color("black")


# ------------------------------------------
# 11. Add title
# ------------------------------------------

ax.set_title(
    "Topic Distribution of Pilot Comments, 2025",
    fontsize=15,
    pad=18
)


# ------------------------------------------
# 12. Keep the chart circular
# ------------------------------------------

ax.set_aspect("equal")


# ------------------------------------------
# 13. Adjust layout
# ------------------------------------------

plt.tight_layout()


# ------------------------------------------
# 14. Save figure
# ------------------------------------------

plt.savefig(
    "pilot_comments_topic_pie_pretty.png",
    dpi=300,
    bbox_inches="tight"
)


# ------------------------------------------
# 15. Show figure
# ------------------------------------------

plt.show()


# ------------------------------------------
# 16. Download in Google Colab
# ------------------------------------------

from google.colab import files

files.download("pilot_comments_topic_pie_pretty.png")